clair:
  database:
    type: pgsql
    options:
      source: postgresql://postgres:password@postgres:5432?sslmode=disable&statement_timeout=60000
      cachesize: 16384
      paginationkey:

  api:
    addr: "0.0.0.0:6060"
    healthaddr: "0.0.0.0:6061"
    timeout: 900s
    servername:
    cafile:
    keyfile:
    certfile:
  updater:
    interval: 2h
    enabledupdaters:
      - debian
      - ubuntu
      - rhel
      - oracle
      - alpine
      - suse
      - amzn

  notifier:
    attempts: 3
    renotifyinterval: 2h
    http:
      endpoint:
      servername:
      cafile:
      keyfile:
      certfile:
      proxy: